<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtBoxLine2</name>
   <tag></tag>
   <elementGuidId>8bc6d7f3-a4ba-40d9-8b69-cb87295a9366</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name='addressLineTwo']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
