<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtBoxCity</name>
   <tag></tag>
   <elementGuidId>986a0e16-9d0f-4cfc-8d56-6bf9826bfadc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name='city']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
