<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtBoxPhoneNumber</name>
   <tag></tag>
   <elementGuidId>9bb3ab82-39f3-4616-af96-d9ce3337c3d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name='phoneNumber']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
