<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtBoxDOB</name>
   <tag></tag>
   <elementGuidId>8d8a40a7-48e8-411a-849a-7e4bd36cf289</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[placeholder='DD/MM/YYYY']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
