<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtBoxState</name>
   <tag></tag>
   <elementGuidId>f753e664-896b-480a-b8e9-969aea911b3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name='state']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
