<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtBoxLine1</name>
   <tag></tag>
   <elementGuidId>b68ab5e0-eb51-45f9-876f-435a89985f41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.location-search-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
