<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Paypal</name>
   <tag></tag>
   <elementGuidId>5ccbd93c-cb0d-4b78-bb59-5006430d4740</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[label='Paypal']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
