<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>labelCode</name>
   <tag></tag>
   <elementGuidId>4296fb04-54fc-429b-9021-b2428f6971ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table//tr[3]/td//div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>//table//tr[3]/td/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
