<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtboxEmployerRole</name>
   <tag></tag>
   <elementGuidId>e4e80bf5-1fd4-4dac-aac9-d5d9cbf0d021</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name='jobTitle']</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
