<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtboxTeamSize</name>
   <tag></tag>
   <elementGuidId>48ad611c-1f76-4e79-a689-f0df33a4b834</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name='name']</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='teamPreference']/ancestor::div[contains(@class,'custom-multi-select')]//input[contains(@id,'react-select-')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
