<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtBoxCompanySize</name>
   <tag></tag>
   <elementGuidId>42769f2c-24b1-4ca4-83b7-69429568f895</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name='firstName']</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='companyType']/ancestor::div[contains(@class,'custom-multi-select')]//input[contains(@id,'react-select-')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
