<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnExpand</name>
   <tag></tag>
   <elementGuidId>82706ff8-2ed7-4b25-bd76-537595c9f23d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.navbar-toggler-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div/nav/div/div/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navbar-toggler-icon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[@class=&quot;styles__PrivateWrapper-sc-1edet86-0 igGoZy private-layout&quot;]/div[@class=&quot;header-style__HeaderNav-sc-196epht-4 fqsaJt&quot;]/nav[@class=&quot;header-style__FixedNavbar-sc-196epht-5 dijDDK sidebar-close navbar&quot;]/div[@class=&quot;header-style__NavbarContainer-sc-196epht-10 dWhXEN container-fluid&quot;]/div[@class=&quot;d-flex align-items-center navbar-expand-md&quot;]/button[@class=&quot;header-style__HamburgerToggle-sc-196epht-3 bKMdJk navbar-toggler&quot;]/span[@class=&quot;navbar-toggler-icon&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div/nav/div/div/button/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
   </webElementXpaths>
</WebElementEntity>
