<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Langauge</name>
   <tag></tag>
   <elementGuidId>a3a2d1bb-c3db-450b-a25a-b695fcb219f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[.='Language']/ancestor::div[contains(@class,'position-relative')]//input[contains(@id,'react-select-')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name='languageCount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
