<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtBoxLocation</name>
   <tag></tag>
   <elementGuidId>8a1c0095-498d-491f-a166-17ba58a689be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name='locationName']</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>input[name='locationName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
