<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtboxVAT</name>
   <tag></tag>
   <elementGuidId>ef591723-c9ab-4726-890f-31470d0b433d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name='vatNumber']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
