<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtboxCompanyRegNumber</name>
   <tag></tag>
   <elementGuidId>65a44a70-d592-45c9-b46e-9c7978aa0bb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name='registeredNumber']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
