<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtboxBrandName</name>
   <tag></tag>
   <elementGuidId>ced252e8-08e3-4e9e-af05-e57079239028</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name='brand']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
