<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>City</name>
   <tag></tag>
   <elementGuidId>9e6212f3-5011-430a-a9ad-522d4dd8c099</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name='city']</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
