<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Linkedin</name>
   <tag></tag>
   <elementGuidId>aff430a5-26c1-4b0b-aded-b665c0b5a39f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name='linkedInUrl']</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
