<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Postcode</name>
   <tag></tag>
   <elementGuidId>dddd8040-11cc-4424-881d-db39e600ade3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name='postcode']</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
