<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Website</name>
   <tag></tag>
   <elementGuidId>206a8a02-ce3f-415e-9d38-a3d1633aed47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name='websiteUrl']</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
