<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtboxProjectSummary</name>
   <tag></tag>
   <elementGuidId>bab42775-1262-440a-8d8f-2ecf1753a717</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>input[name='projectName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name='projectSummary']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
