<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtboxProjectName</name>
   <tag></tag>
   <elementGuidId>8ee45f6b-32fc-443f-92a0-d023c2008df8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>input[name='projectName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name='projectName']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
