<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Friday</name>
   <tag></tag>
   <elementGuidId>f32ac17e-ad40-43de-886a-1fcbbd2e193d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name='Friday']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='Friday']/following-sibling::input[@name='hour24']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
