<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Thursday</name>
   <tag></tag>
   <elementGuidId>1d689d1c-2c2d-42de-a300-05045a2bd2ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name='Thursday']//input[@name='Monday']/following-sibling::input[@name='hour24']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='Thursday']/following-sibling::input[@name='hour24']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
