<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tuesday</name>
   <tag></tag>
   <elementGuidId>215ed768-c013-4084-a065-131aa06cdab9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name='Tuesday']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='Tuesday']/following-sibling::input[@name='hour24']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
