<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtboxRatePerHour</name>
   <tag></tag>
   <elementGuidId>4230fdbf-6118-4029-98ea-3e26151dcb1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name='briefRatePerHour']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>input[name='projectName']</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
