<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtboxJobTitle</name>
   <tag></tag>
   <elementGuidId>a267b9ef-a4be-4a6e-8a35-a852ae6fc353</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name='briefTitle']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'header-style')]//button[@name='client_add_brief']</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
